version: "3"
services:
  web:
    build: .
    image: cookiehoodie/cs3219-otot-b
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - MONGO_URI=mongodb://mongo:27017